### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2-docs#25]
Opening this issue so we can throw some ideas for a new "Recipes" section.

**Recipes** = code snippets that people can copy/paste and work out of the box. Let's think about the top things that we do all the time, and then we can add more complex ones.

Some ideas:

- Get the current balance of the connected account
- Read a uint from a contract and display it in a nice way (maybe with & without params)
- Write to a contract with & without a param (setGreeting?) + button that onclick executes writeAsync
- Imperatively writing to a contract (passing args to writeAsync)
- Events...

---

We can start creating the section and adding some of these.

**Comment by technophile-04** [comment]
- maybe an example of how to use `useTransactor` with wagmi's `useContractWrite` so that it shows nice transaction toast's to end user

or maybe we could add `useTransactor` in hooks section and explain it there, here is the gist which I just shared in TG support chat : https://gist.github.com/technophile-04/397983065d03d946383ef6cb63628bbf 

--- 

> We can start creating the section and adding some of these.

💯💯

**Comment by Pabl0cks** [comment]
Closing, we can keep iterating and adding new recipes in the future
